memcachephp:
  image: dockerizedrupal/memcachephp:latest
  hostname: memcachephp
  ports:
    - "80:80"
    - "443:443"
  volumes_from:
    - memcachephpdata
  environment:
    - SERVER_NAME=localhost
    - TIMEOUT=300
    - PROTOCOLS=https,http
    - USERNAME=root
    - PASSWORD=root
memcachephpdata:
  image: dockerizedrupal/data:latest
  hostname: memcachephpdata
  volumes:
    - /memcachephp
