memcachephp:
  image: dockerizedrupal/memcachephp:1.0.8
  hostname: memcachephp
  ports:
    - "80:80"
    - "443:443"
  volumes_from:
    - memcachephp-data
  environment:
    - SERVER_NAME=localhost
    - TIMEZONE=Etc/UTC
    - TIMEOUT=300
    - PROTOCOLS=https,http
    - HTTP_BASIC_AUTH_USERNAME=container
    - HTTP_BASIC_AUTH_PASSWORD=
memcachephp-data:
  image: dockerizedrupal/data:1.0.3
  hostname: memcachephp-data
  volumes:
    - /memcachephp
